# Generated by Django 4.2.24 on 2025-11-10 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='accesorios/')),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bicicletas/')),
                ('tipo', models.CharField(choices=[('mountain', 'Montaña'), ('road', 'Ruta'), ('hybrid', 'Híbrida'), ('bmx', 'BMX'), ('electric', 'Eléctrica'), ('folding', 'Plegable'), ('cruiser', 'Cruiser'), ('city', 'Urbana')], default='city', max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BicicletaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('trek', 'Trek'), ('giant', 'Giant'), ('specialized', 'Specialized'), ('cannondale', 'Cannondale'), ('scott', 'Scott'), ('bianchi', 'Bianchi'), ('orbea', 'Orbea'), ('merida', 'Merida'), ('other', 'Otra')], max_length=50)),
                ('color', models.CharField(choices=[('negro', 'Negro'), ('blanco', 'Blanco'), ('rojo', 'Rojo'), ('azul', 'Azul'), ('verde', 'Verde'), ('amarillo', 'Amarillo'), ('naranja', 'Naranja'), ('gris', 'Gris'), ('multicolor', 'Multicolor')], max_length=20)),
                ('tipo', models.CharField(choices=[('mountain', 'Montaña'), ('road', 'Ruta'), ('hybrid', 'Híbrida'), ('bmx', 'BMX'), ('electric', 'Eléctrica'), ('folding', 'Plegable'), ('cruiser', 'Cruiser'), ('city', 'Urbana')], max_length=20)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('notas_adicionales', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrdenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='repuestos/')),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('numero_parte', models.CharField(blank=True, max_length=100)),
                ('compatibilidad', models.TextField(blank=True)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('pastillas_freno', 'Cambio pastillas freno'), ('lubricacion_cadena', 'Lubricación de cadena'), ('centrado_ruedas', 'Centrado ruedas'), ('cambio_ruedas_fundas', 'Cambio de ruedas y fundas'), ('limpieza_profunda', 'Limpieza profunda')], max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.bicicletacliente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.cliente')),
                ('servicios', models.ManyToManyField(through='menu.ItemOrdenMantenimiento', to='menu.serviciomantenimiento')),
            ],
        ),
        migrations.AddField(
            model_name='itemordenmantenimiento',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ordenmantenimiento'),
        ),
        migrations.AddField(
            model_name='itemordenmantenimiento',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.serviciomantenimiento'),
        ),
        migrations.AddField(
            model_name='bicicletacliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.cliente'),
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(choices=[('bicicleta', 'Bicicleta'), ('repuesto', 'Repuesto'), ('accesorio', 'Accesorio')], max_length=20)),
                ('producto_id', models.IntegerField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'tipo_producto', 'producto_id')},
            },
        ),
    ]
