# Generated by Django 4.2.24 on 2025-09-10 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicicletaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('trek', 'Trek'), ('giant', 'Giant'), ('specialized', 'Specialized'), ('cannondale', 'Cannondale'), ('scott', 'Scott'), ('bianchi', 'Bianchi'), ('orbea', 'Orbea'), ('merida', 'Merida'), ('other', 'Otra')], max_length=50)),
                ('color', models.CharField(choices=[('negro', 'Negro'), ('blanco', 'Blanco'), ('rojo', 'Rojo'), ('azul', 'Azul'), ('verde', 'Verde'), ('amarillo', 'Amarillo'), ('naranja', 'Naranja'), ('gris', 'Gris'), ('multicolor', 'Multicolor')], max_length=20)),
                ('tipo', models.CharField(choices=[('mountain', 'Montaña'), ('road', 'Ruta'), ('hybrid', 'Híbrida'), ('bmx', 'BMX'), ('electric', 'Eléctrica'), ('folding', 'Plegable'), ('cruiser', 'Cruiser'), ('city', 'Urbana')], max_length=20)),
                ('año', models.IntegerField(blank=True, null=True)),
                ('notas_adicionales', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrdenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('pastillas_freno', 'Cambio pastillas freno'), ('lubricacion_cadena', 'Lubricación de cadena'), ('centrado_ruedas', 'Centrado ruedas'), ('cambio_ruedas_fundas', 'Cambio de ruedas y fundas'), ('limpieza_profunda', 'Limpieza profunda')], max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.bicicletacliente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.cliente')),
                ('servicios', models.ManyToManyField(through='menu.ItemOrdenMantenimiento', to='menu.serviciomantenimiento')),
            ],
        ),
        migrations.AddField(
            model_name='itemordenmantenimiento',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ordenmantenimiento'),
        ),
        migrations.AddField(
            model_name='itemordenmantenimiento',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.serviciomantenimiento'),
        ),
        migrations.AddField(
            model_name='bicicletacliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.cliente'),
        ),
    ]
