# Generated by Django 4.2.24 on 2025-09-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_bicicletacliente_cliente_itemordenmantenimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='modelo_bicicleta',
            field=models.CharField(default='modelo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='tipo_bicicleta',
            field=models.CharField(default='modelo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviciomantenimiento',
            name='descripcion',
            field=models.TextField(default='modelo'),
            preserve_default=False,
        ),
    ]
