# Generated by Django 4.2.24 on 2025-09-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_bicicleta_modelo_bicicleta_bicicleta_tipo_bicicleta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='accesorio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='accesorios/'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='repuestos/'),
        ),
    ]
