# Generated by Django 5.2.6 on 2025-10-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_cliente_telefono_accesorio_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicicleta',
            name='modelo_bicicleta',
        ),
        migrations.RemoveField(
            model_name='bicicleta',
            name='tipo_bicicleta',
        ),
        migrations.RemoveField(
            model_name='bicicletacliente',
            name='año',
        ),
        migrations.AddField(
            model_name='accesorio',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='tipo',
            field=models.CharField(choices=[('mountain', 'Montaña'), ('road', 'Ruta'), ('hybrid', 'Híbrida'), ('bmx', 'BMX'), ('electric', 'Eléctrica'), ('folding', 'Plegable'), ('cruiser', 'Cruiser'), ('city', 'Urbana')], default='city', max_length=50),
        ),
        migrations.AddField(
            model_name='bicicletacliente',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='compatibilidad',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='numero_parte',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='bicicletas/'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='modelo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemordenmantenimiento',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviciomantenimiento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviciomantenimiento',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
